MOCK_HUID_DB = {
    "A8F2X9": {
        "huid": "A8F2X9",
        "jeweller_name": "Tanishq Jewellers (Titan Company Ltd.)",
        "registration_no": "REG/DEL/2023/8890",
        "ahc_center": "Delhi Assaying & Hallmarking Centre, Karol Bagh",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Ring / Band",
        "gross_weight": "8.45 grams",
        "hallmarking_date": "15-Aug-2025",
        "status": "Verified & Authentic",
    },
    "AZ4K19": {
        "huid": "AZ4K19",
        "jeweller_name": "Kalyan Jewellers India Ltd.",
        "registration_no": "REG/MUM/2022/1102",
        "ahc_center": "Mumbai Central AHC",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Gold Bangle",
        "gross_weight": "14.20 grams",
        "hallmarking_date": "10-Jan-2026",
        "status": "Verified & Authentic",
    },
    "B9C3M1": {
        "huid": "B9C3M1",
        "jeweller_name": "Malabar Gold & Diamonds",
        "registration_no": "REG/BLR/2023/4521",
        "ahc_center": "Bangalore Precision Hallmarking Centre, Jayanagar",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Necklace",
        "gross_weight": "32.10 grams",
        "hallmarking_date": "04-Feb-2025",
        "status": "Verified & Authentic",
    },
    "C1D4K2": {
        "huid": "C1D4K2",
        "jeweller_name": "Joyalukkas India Pvt Ltd",
        "registration_no": "REG/COCH/2022/7812",
        "ahc_center": "Kochi Assaying & Hallmarking Services",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Earrings (Pair)",
        "gross_weight": "6.80 grams",
        "hallmarking_date": "18-Mar-2025",
        "status": "Verified & Authentic",
    },
    "D2E5L3": {
        "huid": "D2E5L3",
        "jeweller_name": "PC Jeweller Ltd",
        "registration_no": "REG/DEL/2021/3341",
        "ahc_center": "North India Hallmarking Bureau, South Ext",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Diamond Studded Gold Pendant",
        "gross_weight": "4.15 grams",
        "hallmarking_date": "22-Apr-2025",
        "status": "Verified & Authentic",
    },
    "E3F6M4": {
        "huid": "E3F6M4",
        "jeweller_name": "Bhima Jewels",
        "registration_no": "REG/TVM/2023/9012",
        "ahc_center": "Thiruvananthapuram AHC",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Chain",
        "gross_weight": "16.50 grams",
        "hallmarking_date": "11-May-2025",
        "status": "Verified & Authentic",
    },
    "F4G7N5": {
        "huid": "F4G7N5",
        "jeweller_name": "Senco Gold & Diamonds",
        "registration_no": "REG/KOL/2022/5567",
        "ahc_center": "Kolkata Central Assaying Centre, Bowbazar",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Mangalsutra",
        "gross_weight": "12.30 grams",
        "hallmarking_date": "01-Jun-2025",
        "status": "Verified & Authentic",
    },
    "G5H8P6": {
        "huid": "G5H8P6",
        "jeweller_name": "GRT Jewellers (G R Thanga Maligai)",
        "registration_no": "REG/CHE/2021/2289",
        "ahc_center": "Chennai City Hallmarking Centre, T. Nagar",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Kadam Bangle",
        "gross_weight": "24.75 grams",
        "hallmarking_date": "19-Jul-2025",
        "status": "Verified & Authentic",
    },
    "H6J9Q7": {
        "huid": "H6J9Q7",
        "jeweller_name": "CaratLane Trading Pvt Ltd",
        "registration_no": "REG/BLR/2024/1109",
        "ahc_center": "Karnataka State Assaying Centre, Koramangala",
        "purity": "14K585 (14 Carat - 58.5% Pure Gold)",
        "article_type": "Diamond Gold Bracelet",
        "gross_weight": "5.60 grams",
        "hallmarking_date": "30-Aug-2025",
        "status": "Verified & Authentic",
    },
    "J7K1R8": {
        "huid": "J7K1R8",
        "jeweller_name": "TBZ - Tribhovandas Bhimji Zaveri",
        "registration_no": "REG/MUM/2021/8821",
        "ahc_center": "Zaveri Bazaar Hallmarking Association",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Kada",
        "gross_weight": "38.90 grams",
        "hallmarking_date": "14-Sep-2025",
        "status": "Verified & Authentic",
    },
    "K8L2S9": {
        "huid": "K8L2S9",
        "jeweller_name": "PNG Jewellers (P N Gadgil)",
        "registration_no": "REG/PUN/2022/6634",
        "ahc_center": "Pune City Assaying & Hallmarking",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Nath / Nose Ring",
        "gross_weight": "2.10 grams",
        "hallmarking_date": "05-Oct-2025",
        "status": "Verified & Authentic",
    },
    "L9M3T1": {
        "huid": "L9M3T1",
        "jeweller_name": "Lalithaa Jewellery Mart Pvt Ltd",
        "registration_no": "REG/CHE/2023/4412",
        "ahc_center": "Metro Hallmarking Centre, Chennai",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Haram / Long Necklace",
        "gross_weight": "48.20 grams",
        "hallmarking_date": "28-Oct-2025",
        "status": "Verified & Authentic",
    },
    "M1N4U2": {
        "huid": "M1N4U2",
        "jeweller_name": "Jos Alukkas",
        "registration_no": "REG/TCR/2022/9901",
        "ahc_center": "Thrissur District Hallmarking Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Coin / Bar",
        "gross_weight": "10.00 grams",
        "hallmarking_date": "12-Nov-2025",
        "status": "Verified & Authentic",
    },
    "N2P5V3": {
        "huid": "N2P5V3",
        "jeweller_name": "Orra Fine Jewellery",
        "registration_no": "REG/MUM/2023/3321",
        "ahc_center": "BKC Assaying Centre, Mumbai",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Diamond Gold Engagement Ring",
        "gross_weight": "3.85 grams",
        "hallmarking_date": "01-Dec-2025",
        "status": "Verified & Authentic",
    },
    "P3Q6W4": {
        "huid": "P3Q6W4",
        "jeweller_name": "Khazana Jewellery",
        "registration_no": "REG/HYD/2021/7710",
        "ahc_center": "Hyderabad Gold Assaying Centre, Punjagutta",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Vanki / Armlet",
        "gross_weight": "21.40 grams",
        "hallmarking_date": "20-Dec-2025",
        "status": "Verified & Authentic",
    },
    "Q4R7X5": {
        "huid": "Q4R7X5",
        "jeweller_name": "Kuldip Sons Jewellers",
        "registration_no": "REG/JMH/2022/1089",
        "ahc_center": "Jamshedpur Hallmarking Services",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Jhumka Earrings",
        "gross_weight": "11.60 grams",
        "hallmarking_date": "05-Jan-2026",
        "status": "Verified & Authentic",
    },
    "R5S8Y6": {
        "huid": "R5S8Y6",
        "jeweller_name": "Thangamayil Jewellery Ltd",
        "registration_no": "REG/MAD/2022/4456",
        "ahc_center": "Madurai Gold Assaying Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Waist Belt / Oddiyanam",
        "gross_weight": "85.30 grams",
        "hallmarking_date": "18-Jan-2026",
        "status": "Verified & Authentic",
    },
    "S6T9Z7": {
        "huid": "S6T9Z7",
        "jeweller_name": "Vaibhav Global / Vaibhav Jewellers",
        "registration_no": "REG/VIZ/2023/6612",
        "ahc_center": "Visakhapatnam Hallmarking Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Payal / Anklet Accent",
        "gross_weight": "9.70 grams",
        "hallmarking_date": "02-Feb-2026",
        "status": "Verified & Authentic",
    },
    "T7U1A8": {
        "huid": "T7U1A8",
        "jeweller_name": "Anand Milk & Fine Jewels",
        "registration_no": "REG/AMD/2023/1234",
        "ahc_center": "Ahmedabad Standard Assaying Bureau",
        "purity": "20K833 (20 Carat - 83.3% Pure Gold)",
        "article_type": "Gold Antique Pendant",
        "gross_weight": "7.25 grams",
        "hallmarking_date": "14-Feb-2026",
        "status": "Verified & Authentic",
    },
    "U8V2B9": {
        "huid": "U8V2B9",
        "jeweller_name": "Chheda Jewellers",
        "registration_no": "REG/MUM/2024/9911",
        "ahc_center": "Dadar Hallmarking Facility, Mumbai",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Brooch",
        "gross_weight": "6.10 grams",
        "hallmarking_date": "25-Feb-2026",
        "status": "Verified & Authentic",
    },
    "V9W3C1": {
        "huid": "V9W3C1",
        "jeweller_name": "Kalyanam Jewellers",
        "registration_no": "REG/LKO/2022/5543",
        "ahc_center": "Lucknow Assaying Centre, Hazratganj",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Maang Tikka",
        "gross_weight": "8.90 grams",
        "hallmarking_date": "08-Mar-2026",
        "status": "Verified & Authentic",
    },
    "W1X4D2": {
        "huid": "W1X4D2",
        "jeweller_name": "Melorra (August Jewelry Pvt Ltd)",
        "registration_no": "REG/BLR/2023/8810",
        "ahc_center": "Bengaluru Digital AHC",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Lightweight Gold Nose Pin",
        "gross_weight": "0.85 grams",
        "hallmarking_date": "20-Mar-2026",
        "status": "Verified & Authentic",
    },
    "X2Y5E3": {
        "huid": "X2Y5E3",
        "jeweller_name": "Bluestone Jewellery & Lifestyle Pvt Ltd",
        "registration_no": "REG/BLR/2022/3390",
        "ahc_center": "Whitefield Hallmarking Centre, Bengaluru",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Gold & Gemstone Studs",
        "gross_weight": "3.40 grams",
        "hallmarking_date": "01-Apr-2026",
        "status": "Verified & Authentic",
    },
    "Y3Z6F4": {
        "huid": "Y3Z6F4",
        "jeweller_name": "Shree Ganesh Jewellery House",
        "registration_no": "REG/KOL/2021/7788",
        "ahc_center": "Salt Lake Assaying Centre, Kolkata",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Choker Necklace",
        "gross_weight": "28.60 grams",
        "hallmarking_date": "11-Apr-2026",
        "status": "Verified & Authentic",
    },
    "Z4A7G5": {
        "huid": "Z4A7G5",
        "jeweller_name": "Kirtilals (Kirtilal Kalidas Jewellery)",
        "registration_no": "REG/CBE/2022/1156",
        "ahc_center": "Coimbatore Assaying & Hallmarking",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Diamond Bangle Set",
        "gross_weight": "19.80 grams",
        "hallmarking_date": "22-Apr-2026",
        "status": "Verified & Authentic",
    },
    "A5B8H6": {
        "huid": "A5B8H6",
        "jeweller_name": "Prince Jewellery",
        "registration_no": "REG/CHE/2023/6743",
        "ahc_center": "Cathedral Road AHC, Chennai",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Antique Kante",
        "gross_weight": "35.40 grams",
        "hallmarking_date": "03-May-2026",
        "status": "Verified & Authentic",
    },
    "B6C9J7": {
        "huid": "B6C9J7",
        "jeweller_name": "Senco Gold Products Pvt Ltd",
        "registration_no": "REG/PAT/2022/9981",
        "ahc_center": "Patna Central Hallmarking Bureau",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Bala / Bangle",
        "gross_weight": "15.10 grams",
        "hallmarking_date": "15-May-2026",
        "status": "Verified & Authentic",
    },
    "C7D1K8": {
        "huid": "C7D1K8",
        "jeweller_name": "Hazoorilal Legacy Jewellers",
        "registration_no": "REG/DEL/2021/4402",
        "ahc_center": "South Extension AHC, New Delhi",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Uncut Diamond (Polki) Gold Necklace",
        "gross_weight": "54.20 grams",
        "hallmarking_date": "27-May-2026",
        "status": "Verified & Authentic",
    },
    "D8E2L9": {
        "huid": "D8E2L9",
        "jeweller_name": "Motisons Jewellers Ltd",
        "registration_no": "REG/JAI/2023/1178",
        "ahc_center": "Jaipur Johri Bazaar Hallmarking Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Kundan Earrings",
        "gross_weight": "13.90 grams",
        "hallmarking_date": "08-Jun-2026",
        "status": "Verified & Authentic",
    },
    "E9F3M1": {
        "huid": "E9F3M1",
        "jeweller_name": "Ranka Jewellers",
        "registration_no": "REG/PUN/2022/3310",
        "ahc_center": "Laxmi Road AHC, Pune",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Laxmi Coin Chain",
        "gross_weight": "22.50 grams",
        "hallmarking_date": "19-Jun-2026",
        "status": "Verified & Authentic",
    },
    "F1G4N2": {
        "huid": "F1G4N2",
        "jeweller_name": "Waman Hari Pethe Jewellers",
        "registration_no": "REG/MUM/2021/5590",
        "ahc_center": "Girgaon Assaying Centre, Mumbai",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Bugadi Ear Ornament",
        "gross_weight": "3.10 grams",
        "hallmarking_date": "30-Jun-2026",
        "status": "Verified & Authentic",
    },
    "G2H5P3": {
        "huid": "G2H5P3",
        "jeweller_name": "Bhimji Zaveri & Sons",
        "registration_no": "REG/SUR/2023/8834",
        "ahc_center": "Surat Diamond & Gold Hallmarking Hub",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Chain with Cross Pendant",
        "gross_weight": "10.40 grams",
        "hallmarking_date": "11-Jul-2026",
        "status": "Verified & Authentic",
    },
    "H3J6Q4": {
        "huid": "H3J6Q4",
        "jeweller_name": "Chandukaka Saraf & Sons Pvt Ltd",
        "registration_no": "REG/PUN/2022/7721",
        "ahc_center": "Baramati Assaying Facility",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Kolhapuri Saaj Necklace",
        "gross_weight": "26.80 grams",
        "hallmarking_date": "22-Jul-2026",
        "status": "Verified & Authentic",
    },
    "J4K7R5": {
        "huid": "J4K7R5",
        "jeweller_name": "Chintamani Jewellers",
        "registration_no": "REG/MUM/2023/1045",
        "ahc_center": "Prabhadevi AHC, Mumbai",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Cocktail Ring",
        "gross_weight": "7.90 grams",
        "hallmarking_date": "02-Aug-2026",
        "status": "Verified & Authentic",
    },
    "K5L8S6": {
        "huid": "K5L8S6",
        "jeweller_name": "DP Abhushan Ltd",
        "registration_no": "REG/IND/2022/4489",
        "ahc_center": "Indore Gold Testing & Hallmarking Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Bajuband",
        "gross_weight": "17.30 grams",
        "hallmarking_date": "14-Aug-2026",
        "status": "Verified & Authentic",
    },
    "L6M9T7": {
        "huid": "L6M9T7",
        "jeweller_name": "Manoj Ornaments Pvt Ltd",
        "registration_no": "REG/AGR/2021/6632",
        "ahc_center": "Agra Assaying Bureau",
        "purity": "20K833 (20 Carat - 83.3% Pure Gold)",
        "article_type": "Gold Payal Clasp",
        "gross_weight": "4.50 grams",
        "hallmarking_date": "25-Aug-2026",
        "status": "Verified & Authentic",
    },
    "M7N1U8": {
        "huid": "M7N1U8",
        "jeweller_name": "AABUSHAN Jewellers",
        "registration_no": "REG/BLR/2023/9923",
        "ahc_center": "MG Road AHC, Bengaluru",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Temple Nakshi Pendant",
        "gross_weight": "18.10 grams",
        "hallmarking_date": "05-Sep-2026",
        "status": "Verified & Authentic",
    },
    "N8P2V9": {
        "huid": "N8P2V9",
        "jeweller_name": "Kanshiram Jewellers",
        "registration_no": "REG/KAN/2022/3356",
        "ahc_center": "Kanpur Central Assaying Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Kara / Bracelet",
        "gross_weight": "29.40 grams",
        "hallmarking_date": "16-Sep-2026",
        "status": "Verified & Authentic",
    },
    "P9Q3W1": {
        "huid": "P9Q3W1",
        "jeweller_name": "Talla Jewellers",
        "registration_no": "REG/JMU/2023/7711",
        "ahc_center": "Jammu Tawi Hallmarking Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Bridal Choker",
        "gross_weight": "42.00 grams",
        "hallmarking_date": "27-Sep-2026",
        "status": "Verified & Authentic",
    },
    "Q1R4X2": {
        "huid": "Q1R4X2",
        "jeweller_name": "Ratanlal C. Bafna Jewellers",
        "registration_no": "REG/NSK/2022/8845",
        "ahc_center": "Nashik Assaying Bureau",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Mangalsutra Pendant",
        "gross_weight": "6.70 grams",
        "hallmarking_date": "08-Oct-2026",
        "status": "Verified & Authentic",
    },
    "R2S5Y3": {
        "huid": "R2S5Y3",
        "jeweller_name": "Saravana Stores Elite Diamonds & Gold",
        "registration_no": "REG/CHE/2023/2219",
        "ahc_center": "T Nagar AHC Branch 2, Chennai",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Kasu Mala",
        "gross_weight": "36.80 grams",
        "hallmarking_date": "19-Oct-2026",
        "status": "Verified & Authentic",
    },
    "S3T6Z4": {
        "huid": "S3T6Z4",
        "jeweller_name": "Siddharth Gold & Diamond",
        "registration_no": "REG/GUA/2021/5532",
        "ahc_center": "Guwahati Central Hallmarking Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Axomiya Gohona Earrings",
        "gross_weight": "7.50 grams",
        "hallmarking_date": "30-Oct-2026",
        "status": "Verified & Authentic",
    },
    "T4U7A5": {
        "huid": "T4U7A5",
        "jeweller_name": "Suka Jewellers",
        "registration_no": "REG/MUM/2024/1187",
        "ahc_center": "Thane West Assaying Centre",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Rose Gold Diamond Ring",
        "gross_weight": "3.90 grams",
        "hallmarking_date": "10-Nov-2026",
        "status": "Verified & Authentic",
    },
    "U5V8B6": {
        "huid": "U5V8B6",
        "jeweller_name": "Emerald Jewel Industry India Ltd",
        "registration_no": "REG/CBE/2021/9944",
        "ahc_center": "Emerald Industrial AHC, Coimbatore",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Machine-Made Chain",
        "gross_weight": "14.80 grams",
        "hallmarking_date": "21-Nov-2026",
        "status": "Verified & Authentic",
    },
    "V6W9C7": {
        "huid": "V6W9C7",
        "jeweller_name": "Gitanjali Gems & Jewels",
        "registration_no": "REG/DEL/2022/6610",
        "ahc_center": "Chandni Chowk Hallmarking Centre",
        "purity": "14K585 (14 Carat - 58.5% Pure Gold)",
        "article_type": "Gold Gemstone Ear Studs",
        "gross_weight": "2.90 grams",
        "hallmarking_date": "02-Dec-2026",
        "status": "Verified & Authentic",
    },
    "W7X1D8": {
        "huid": "W7X1D8",
        "jeweller_name": "Mehta Jewellery",
        "registration_no": "REG/CHE/2021/3378",
        "ahc_center": "Mylapore Assaying Centre, Chennai",
        "purity": "18K750 (18 Carat - 75.0% Pure Gold)",
        "article_type": "Diamond Drop Earrings",
        "gross_weight": "8.15 grams",
        "hallmarking_date": "13-Dec-2026",
        "status": "Verified & Authentic",
    },
    "X8Y2E9": {
        "huid": "X8Y2E9",
        "jeweller_name": "Sri Krishna Diamonds & Jewellery",
        "registration_no": "REG/BLR/2023/5512",
        "ahc_center": "Commercial Street AHC, Bengaluru",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Broad Bangle",
        "gross_weight": "26.30 grams",
        "hallmarking_date": "24-Dec-2026",
        "status": "Verified & Authentic",
    },
    "Y9Z3F1": {
        "huid": "Y9Z3F1",
        "jeweller_name": "Bholanath Gold & Silver Corp",
        "registration_no": "REG/VAR/2022/4410",
        "ahc_center": "Varanasi Heritage Hallmarking Centre",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Rudraksha Pendant",
        "gross_weight": "5.30 grams",
        "hallmarking_date": "04-Jan-2027",
        "status": "Verified & Authentic",
    },
    "Z1A4G2": {
        "huid": "Z1A4G2",
        "jeweller_name": "Shree Kalikambal Jewellers",
        "registration_no": "REG/TRI/2023/8899",
        "ahc_center": "Tiruchirappalli Assaying Hub",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Thali / Mangalsutra Coin",
        "gross_weight": "4.00 grams",
        "hallmarking_date": "15-Jan-2027",
        "status": "Verified & Authentic",
    },
    "A2B5H3": {
        "huid": "A2B5H3",
        "jeweller_name": "Talla Fine Gold & Diamonds",
        "registration_no": "REG/LUD/2024/2201",
        "ahc_center": "Ludhiana Central AHC",
        "purity": "22K916 (22 Carat - 91.6% Pure Gold)",
        "article_type": "Gold Mens Solitaire Ring",
        "gross_weight": "9.80 grams",
        "hallmarking_date": "26-Jan-2027",
        "status": "Verified & Authentic",
    },
}