MOCK_LICENSE_DB = {
    "CML-8700109": {
        "license_number": "CM/L-8700109",
        "manufacturer_name": "Milton Industries Ltd.",
        "factory_address": "Plot 42, Industrial Area, Haridwar, Uttarakhand - 249401",
        "is_standard": "IS 17803:2022",
        "product_name": "Stainless Steel Drinking Water Bottles",
        "brand": "Milton",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "31-Dec-2027",
    },
    "CML-1234567": {
        "license_number": "CM/L-1234567",
        "manufacturer_name": "Studds Accessories Ltd.",
        "factory_address": "Plot 9, Sector 59, Faridabad, Haryana - 121004",
        "is_standard": "IS 4151:2015",
        "product_name": "Protective Helmets for Two-Wheeler Riders",
        "brand": "Studds",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "15-Oct-2028",
    },
    "CML-8700101": {
        "license_number": "CM/L-8700101",
        "manufacturer_name": "Apex Polymer Solutions Pvt Ltd",
        "factory_address": "Plot 12, Phase II, GIDC Industrial Estate, Ahmedabad, Gujarat - 382445",
        "is_standard": "IS 15410:2003",
        "product_name": "Containers for Packaging of Mineral Water",
        "brand": "ApexPack",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "15-Mar-2027",
    },
    "CML-8700102": {
        "license_number": "CM/L-8700102",
        "manufacturer_name": "Zenith Electricals India Ltd",
        "factory_address": "Survey No. 88, Sector 5, IMT Manesar, Gurugram, Haryana - 122051",
        "is_standard": "IS 694:2010",
        "product_name": "PVC Insulated Cables for Working Voltages up to 1100V",
        "brand": "ZenWire",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "30-Jun-2028",
    },
    "CML-8700103": {
        "license_number": "CM/L-8700103",
        "manufacturer_name": "Surya Steel & Alloys Pvt Ltd",
        "factory_address": "Gat No. 405, Sanaswadi, Taluka Shirur, Pune, Maharashtra - 412208",
        "is_standard": "IS 1786:2008",
        "product_name": "High Strength Deformed Steel Bars (TMT)",
        "brand": "SuryaTMT",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "31-Oct-2026",
    },
    "CML-8700104": {
        "license_number": "CM/L-8700104",
        "manufacturer_name": "Oceanic Aqua Beverages",
        "factory_address": "Khasra No. 112, Village Selaqui, Dehradun, Uttarakhand - 248197",
        "is_standard": "IS 14543:2016",
        "product_name": "Packaged Drinking Water",
        "brand": "AquaPure",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "12-Jan-2028",
    },
    "CML-8700105": {
        "license_number": "CM/L-8700105",
        "manufacturer_name": "GreenTech Safety Glass Ltd",
        "factory_address": "Plot 5A, SIPCOT Industrial Park, Sriperumbudur, Tamil Nadu - 602105",
        "is_standard": "IS 2553 (Part 1):2018",
        "product_name": "Safety Glass for Architectural Use",
        "brand": "ShieldGlass",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "31-Aug-2027",
    },
    "CML-8700106": {
        "license_number": "CM/L-8700106",
        "manufacturer_name": "Himalaya Cement Products",
        "factory_address": "Industrial Area Phase 1, Baddi, Solan, Himachal Pradesh - 173205",
        "is_standard": "IS 1489 (Part 1):2015",
        "product_name": "Portland Pozzolana Cement (Flyash Based)",
        "brand": "HimaCem",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "30-Nov-2026",
    },
    "CML-8700107": {
        "license_number": "CM/L-8700107",
        "manufacturer_name": "Nova Appliances Pvt Ltd",
        "factory_address": "Plot 33, Electronic City, Sector 18, Noida, Uttar Pradesh - 201301",
        "is_standard": "IS 302 (Part 2/Sec 3):2007",
        "product_name": "Electric Iron",
        "brand": "NovaPress",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "28-Feb-2029",
    },
    "CML-8700108": {
        "license_number": "CM/L-8700108",
        "manufacturer_name": "Bharat Agro Chemicals",
        "factory_address": "Plot 78, MIDC Tarapur, Palghar, Maharashtra - 401506",
        "is_standard": "IS 2567:1978",
        "product_name": "Malathion Emulsifiable Concentrates",
        "brand": "AgroGuard",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "15-Sep-2027",
    },
    "CML-8700110": {
        "license_number": "CM/L-8700110",
        "manufacturer_name": "Kaveri Piping Systems Pvt Ltd",
        "factory_address": "Plot 88, KIADB Industrial Area, Hoskote, Bengaluru, Karnataka - 562114",
        "is_standard": "IS 4985:2021",
        "product_name": "Unplasticized PVC Pipes for Potable Water Supplies",
        "brand": "KaveriPipe",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "10-May-2028",
    },
    "CML-8700111": {
        "license_number": "CM/L-8700111",
        "manufacturer_name": "Titanium Auto Components",
        "factory_address": "Gat No. 12, Chakan Industrial Area, Pune, Maharashtra - 410501",
        "is_standard": "IS 13061:1991",
        "product_name": "Automotive Helmets for Two-Wheeler Riders",
        "brand": "TitanArmor",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "30-Apr-2027",
    },
    "CML-8700112": {
        "license_number": "CM/L-8700112",
        "manufacturer_name": "Radiant LED Lighting Solutions",
        "factory_address": "Plot 4, Tech Park, Mohali, Punjab - 160055",
        "is_standard": "IS 16102 (Part 1):2012",
        "product_name": "Self-Ballasted LED Lamps for General Lighting Services",
        "brand": "RadiantGlow",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "20-Jul-2027",
    },
    "CML-8700113": {
        "license_number": "CM/L-8700113",
        "manufacturer_name": "Vanguard Footwear Corp",
        "factory_address": "Leather Complex, Kapurthala Road, Jalandhar, Punjab - 144021",
        "is_standard": "IS 15298 (Part 2):2016",
        "product_name": "Safety Footwear for Industrial Applications",
        "brand": "VanShield",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "11-Nov-2026",
    },
    "CML-8700114": {
        "license_number": "CM/L-8700114",
        "manufacturer_name": "Pinnacle Gas Appliances Ltd",
        "factory_address": "Plot 102, Sector 59, Faridabad, Haryana - 121004",
        "is_standard": "IS 4246:2002",
        "product_name": "Domestic Gas Stoves for Use with LPG",
        "brand": "PinnacleFlame",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "31-Dec-2028",
    },
    "CML-8700115": {
        "license_number": "CM/L-8700115",
        "manufacturer_name": "Ecolight Batteries India",
        "factory_address": "Survey No. 45, Pantnagar Industrial Estate, Udham Singh Nagar, Uttarakhand - 263153",
        "is_standard": "IS 16046 (Part 2):2018",
        "product_name": "Secondary Cells Containing Alkaline / Non-Acid Electrolytes",
        "brand": "EcoCell",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "18-Aug-2027",
    },
    "CML-8700116": {
        "license_number": "CM/L-8700116",
        "manufacturer_name": "Godavari Food Products",
        "factory_address": "Plot 15, APIIC Industrial Park, Vijayawada, Andhra Pradesh - 520007",
        "is_standard": "IS 11536:2007",
        "product_name": "Processed Cereal Based Complementary Foods",
        "brand": "NutriBites",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "05-Feb-2027",
    },
    "CML-8700117": {
        "license_number": "CM/L-8700117",
        "manufacturer_name": "Vardhaman Textiles & Threads Ltd",
        "factory_address": "Focal Point, Ludhiana, Punjab - 141010",
        "is_standard": "IS 1720:1978",
        "product_name": "Cotton Sewing Threads",
        "brand": "VardhmanThread",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "25-Oct-2028",
    },
    "CML-8700118": {
        "license_number": "CM/L-8700118",
        "manufacturer_name": "United Plywood Industries",
        "factory_address": "NH 37, Changsari, Kamrup, Assam - 781101",
        "is_standard": "IS 303:1989",
        "product_name": "Plywood for General Purposes",
        "brand": "UniPly",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "14-May-2027",
    },
    "CML-8700119": {
        "license_number": "CM/L-8700119",
        "manufacturer_name": "Precision Tools & Gauges Ltd",
        "factory_address": "Peenya Industrial Area 3rd Stage, Bengaluru, Karnataka - 560058",
        "is_standard": "IS 2103:1980",
        "product_name": "Engineers Steel Rules",
        "brand": "PreciseRule",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "30-Sep-2027",
    },
    "CML-8700120": {
        "license_number": "CM/L-8700120",
        "manufacturer_name": "Solaris Energy Modules",
        "factory_address": "Plot 20, Solar Park, Charanka, Patan, Gujarat - 384285",
        "is_standard": "IS 14286:2010",
        "product_name": "Crystalline Silicon Terrestrial Photovoltaic Modules",
        "brand": "SolarisPro",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "01-Dec-2028",
    },
    "CML-8700121": {
        "license_number": "CM/L-8700121",
        "manufacturer_name": "Metropolis Sanitaryware",
        "factory_address": "8-A National Highway, Morbi, Gujarat - 363642",
        "is_standard": "IS 2556 (Part 2):2004",
        "product_name": "Vitreous Sanitary Appliances - Wash Basins",
        "brand": "MetroSan",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "19-Apr-2027",
    },
    "CML-8700122": {
        "license_number": "CM/L-8700122",
        "manufacturer_name": "Shree Ram Chemicals",
        "factory_address": "Plot 55, GIDC Dahej, Bharuch, Gujarat - 392130",
        "is_standard": "IS 252:2013",
        "product_name": "Caustic Soda, Pure and Technical",
        "brand": "ShreeChem",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "30-Jul-2028",
    },
    "CML-8700123": {
        "license_number": "CM/L-8700123",
        "manufacturer_name": "AeroSpace Lubricants",
        "factory_address": "Survey No. 76, Panya, Vadodara, Gujarat - 390019",
        "is_standard": "IS 496:2002",
        "product_name": "Automotive Internal Combustion Engine Oils",
        "brand": "AeroLube",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "15-Aug-2027",
    },
    "CML-8700124": {
        "license_number": "CM/L-8700124",
        "manufacturer_name": "Royal Furniture & Office Decor",
        "factory_address": "Plot 99, Kirti Nagar Industrial Area, New Delhi - 110015",
        "is_standard": "IS 3663:1991",
        "product_name": "Metal Chairs for Office Purpose",
        "brand": "RoyalSeat",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "10-Nov-2026",
    },
    "CML-8700125": {
        "license_number": "CM/L-8700125",
        "manufacturer_name": "Pratap Extrusions Pvt Ltd",
        "factory_address": "Plot 14, RIICO Industrial Area, Bhiwadi, Rajasthan - 301019",
        "is_standard": "IS 733:1983",
        "product_name": "Wrought Aluminium and Aluminium Alloy Bars, Rods and Sections",
        "brand": "PratapAlu",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "22-Mar-2028",
    },
    "CML-8700126": {
        "license_number": "CM/L-8700126",
        "manufacturer_name": "BlueStar Refrigeration India",
        "factory_address": "Plot 1, Kala Amb Industrial Area, Sirmaur, Himachal Pradesh - 173030",
        "is_standard": "IS 14750:2000",
        "product_name": "Household Frost-Free Refrigerators",
        "brand": "CoolStar",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "05-Jun-2027",
    },
    "CML-8700127": {
        "license_number": "CM/L-8700127",
        "manufacturer_name": "Lotus Medical Disposables",
        "factory_address": "Plot 40, KIADB Hardware Park, Devanahalli, Bengaluru, Karnataka - 562110",
        "is_standard": "IS 10654:2002",
        "product_name": "Hypodermic Syringes for Single Use Only",
        "brand": "LotusMed",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "17-Sep-2028",
    },
    "CML-8700128": {
        "license_number": "CM/L-8700128",
        "manufacturer_name": "Crest Paints & Coatings",
        "factory_address": "Plot 220, Industrial Area Phase 2, Panchkula, Haryana - 134113",
        "is_standard": "IS 101 (Part 1):1989",
        "product_name": "Ready Mixed Paint, Air Drying, Enamel",
        "brand": "CrestCoat",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "31-Jan-2027",
    },
    "CML-8700129": {
        "license_number": "CM/L-8700129",
        "manufacturer_name": "Vidyut Transformers Corp",
        "factory_address": "Plot 67, Mandideep Industrial Area, Bhopal, Madhya Pradesh - 462046",
        "is_standard": "IS 1180 (Part 1):2014",
        "product_name": "Outdoor Type Oil Immersed Distribution Transformers",
        "brand": "VidyutPower",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "08-Oct-2027",
    },
    "CML-8700130": {
        "license_number": "CM/L-8700130",
        "manufacturer_name": "Supertech Elevators India",
        "factory_address": "Survey 34, Khed City, Khed, Pune, Maharashtra - 410505",
        "is_standard": "IS 14665 (Part 3):2000",
        "product_name": "Electric Traction Lifts for Passenger Transport",
        "brand": "SuperLift",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "19-Dec-2028",
    },
    "CML-8700131": {
        "license_number": "CM/L-8700131",
        "manufacturer_name": "AgroGold Organic Fertilizers",
        "factory_address": "Village Kheri, NH 1, Karnal, Haryana - 132001",
        "is_standard": "IS 2961:1973",
        "product_name": "Single Superphosphate (Powdered)",
        "brand": "AgroGold",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "28-May-2027",
    },
    "CML-8700132": {
        "license_number": "CM/L-8700132",
        "manufacturer_name": "AeroFlex Rubber Hose Ltd",
        "factory_address": "Plot 11, Belagavi Industrial Estate, Belagavi, Karnataka - 590011",
        "is_standard": "IS 447:1988",
        "product_name": "Rubber Hose for Welding and Cutting Operations",
        "brand": "FlexHose",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "14-Feb-2028",
    },
    "CML-8700133": {
        "license_number": "CM/L-8700133",
        "manufacturer_name": "Kiran Glass Containers",
        "factory_address": "Plot 80, Firozabad Industrial Zone, Firozabad, Uttar Pradesh - 283203",
        "is_standard": "IS 1107:1986",
        "product_name": "Glass Bottles for Liquid Pharmaceuticals",
        "brand": "KiranGlass",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "30-Sep-2026",
    },
    "CML-8700134": {
        "license_number": "CM/L-8700134",
        "manufacturer_name": "Delta Fire Protection Systems",
        "factory_address": "Plot 105, Wagle Estate, Thane, Maharashtra - 400604",
        "is_standard": "IS 15683:2018",
        "product_name": "Portable Fire Extinguishers - Dry Powder Type",
        "brand": "DeltaGuard",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "21-Jul-2028",
    },
    "CML-8700135": {
        "license_number": "CM/L-8700135",
        "manufacturer_name": "Zenith Solar Water Heaters",
        "factory_address": "Gat No. 89, Shindewadi, Satara Road, Pune, Maharashtra - 412205",
        "is_standard": "IS 12933 (Part 1):2003",
        "product_name": "Solar Flat Plate Collector",
        "brand": "ZenithSolar",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "11-Apr-2027",
    },
    "CML-8700136": {
        "license_number": "CM/L-8700136",
        "manufacturer_name": "Sunrise Dairy Products",
        "factory_address": "Village Anandpur, NH 8, Anand, Gujarat - 388001",
        "is_standard": "IS 1165:2002",
        "product_name": "Milk Powder (Whole and Skimmed)",
        "brand": "SunDairy",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "01-Nov-2027",
    },
    "CML-8700137": {
        "license_number": "CM/L-8700137",
        "manufacturer_name": "National Fasteners India Ltd",
        "factory_address": "Plot 42, Ambattur Industrial Estate, Chennai, Tamil Nadu - 600058",
        "is_standard": "IS 1363 (Part 1):2002",
        "product_name": "Hexagon Head Bolts, Screws and Nuts",
        "brand": "NatBolt",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "23-Dec-2026",
    },
    "CML-8700138": {
        "license_number": "CM/L-8700138",
        "manufacturer_name": "Matrix Batteries & Inverters",
        "factory_address": "Plot 19, Sector 3, IIE Pantnagar, Rudrapur, Uttarakhand - 263153",
        "is_standard": "IS 1651:2013",
        "product_name": "Stationary Lead-Acid Batteries with Tubular Positive Plates",
        "brand": "MatrixPower",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "15-Aug-2028",
    },
    "CML-8700139": {
        "license_number": "CM/L-8700139",
        "manufacturer_name": "Ambica Ceramics & Tiles",
        "factory_address": "Old Ghuntu Road, Morbi, Gujarat - 363642",
        "is_standard": "IS 15622:2017",
        "product_name": "Pressed Ceramic Tiles",
        "brand": "AmbicaTile",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "09-Mar-2027",
    },
    "CML-8700140": {
        "license_number": "CM/L-8700140",
        "manufacturer_name": "EcoPack Corrugated Boxes",
        "factory_address": "Plot 5, Industrial Area Phase 1, Chandigarh - 160002",
        "is_standard": "IS 2771 (Part 1):1990",
        "product_name": "Corrugated Fibreboard Boxes",
        "brand": "EcoBox",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "18-Oct-2027",
    },
    "CML-8700141": {
        "license_number": "CM/L-8700141",
        "manufacturer_name": "Orion Pumps & Motors",
        "factory_address": "Mettupalayam Road, Coimbatore, Tamil Nadu - 641043",
        "is_standard": "IS 8034:2002",
        "product_name": "Submersible Pump-Sets for Clear, Cold Water",
        "brand": "OrionPump",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "31-Jan-2028",
    },
    "CML-8700142": {
        "license_number": "CM/L-8700142",
        "manufacturer_name": "Ganga Edible Oils Pvt Ltd",
        "factory_address": "Khasra 44, Station Road, Morena, Madhya Pradesh - 476001",
        "is_standard": "IS 542:2014",
        "product_name": "Mustard Oil - Specification",
        "brand": "GangaPure",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "12-May-2027",
    },
    "CML-8700143": {
        "license_number": "CM/L-8700143",
        "manufacturer_name": "BrightVision Optical Lenses",
        "factory_address": "Plot 12, SEZ Sector 45, Gurugram, Haryana - 122003",
        "is_standard": "IS 15693:2006",
        "product_name": "Ophthalmic Lenses - Uncut Finished Spectacle Lenses",
        "brand": "BrightLens",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "27-Jun-2028",
    },
    "CML-8700144": {
        "license_number": "CM/L-8700144",
        "manufacturer_name": "Falcon Switchgears Pvt Ltd",
        "factory_address": "Plot 88, MIDC Waluj, Chhatrapati Sambhajinagar, Maharashtra - 431136",
        "is_standard": "IS/IEC 60898 (Part 1):2002",
        "product_name": "Circuit Breakers for Overcurrent Protection (MCB)",
        "brand": "FalconSwitch",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "16-Sep-2027",
    },
    "CML-8700145": {
        "license_number": "CM/L-8700145",
        "manufacturer_name": "Everest Insulation Materials",
        "factory_address": "Survey No. 3, Industrial Suburb, Mysuru, Karnataka - 570008",
        "is_standard": "IS 8183:1993",
        "product_name": "Bonded Mineral Wool Insulation Material",
        "brand": "EverWool",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "04-Dec-2026",
    },
    "CML-8700146": {
        "license_number": "CM/L-8700146",
        "manufacturer_name": "Paramount Leather Goods",
        "factory_address": "Leather Complex, Unnao, Uttar Pradesh - 209801",
        "is_standard": "IS 5677:1986",
        "product_name": "Industrial Safety Gloves Made of Leather",
        "brand": "ParaGrip",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "20-Feb-2028",
    },
    "CML-8700147": {
        "license_number": "CM/L-8700147",
        "manufacturer_name": "Siddharth Paper Mills",
        "factory_address": "Plot 30, Industrial Area, Kashipur, Uttarakhand - 244713",
        "is_standard": "IS 1848:2007",
        "product_name": "Writing and Printing Papers",
        "brand": "SidPaper",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "11-Jul-2027",
    },
    "CML-8700148": {
        "license_number": "CM/L-8700148",
        "manufacturer_name": "UltraShield Waterproofing",
        "factory_address": "Plot 60, GIDC Ankleshwar, Bharuch, Gujarat - 393002",
        "is_standard": "IS 15860:2009",
        "product_name": "Bitumen Based Waterproofing Membranes",
        "brand": "UltraProof",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "08-Oct-2028",
    },
    "CML-8700149": {
        "license_number": "CM/L-8700149",
        "manufacturer_name": "Kishan Tractors & Implements",
        "factory_address": "Industrial Area, Rajkot, Gujarat - 360003",
        "is_standard": "IS 4468 (Part 1):1997",
        "product_name": "Agricultural Tractors Three-Point Linkage",
        "brand": "KishanTrac",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "29-Jan-2027",
    },
    "CML-8700150": {
        "license_number": "CM/L-8700150",
        "manufacturer_name": "MicroTech Electronics",
        "factory_address": "Plot 15, SEEPZ, Andheri East, Mumbai, Maharashtra - 400096",
        "is_standard": "IS 13252 (Part 1):2010",
        "product_name": "Information Technology Equipment - Safety Standards",
        "brand": "MicroPower",
        "status": "OPERATIONAL / ACTIVE",
        "valid_till": "31-Mar-2028",
    },
}